### ISSUE TITLE
Modificación api de eventos con nuevo modelo aprobado

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/eventos_crud#1]
Modificar el api de eventos teniendo en cuenta el nuevo modelo aprobado.

**Comment by JuanPiedrahita** [comment]
Se crea [sql](https://drive.google.com/drive/u/2/folders/1Z0Bky_fvcJAuMeX-vY_nRc_rIAKXYkBj) del modelo aprobado de eventos v8.

**Comment by mafeave** [comment]
1. Agregar 
- 'auto_now_add' al campo FechaCreacion
- 'auto_now' al campo FechaModificacion
de los modelos

2. Actualizar documentación del modelo de datos y las variables de configuración del Readme

**Comment by JuanPiedrahita** [comment]
Cambios realizados.

**Comment by JuanPiedrahita** [comment]
Con el merge se cierra el issue.
