### ISSUE TITLE
Análisis y ajustes del modelo de eventos para manejo de procesos y actividades del calendario académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/eventos_crud#20]
Se debe realizar el análisis y ajustes del modelo de eventos para manejo de procesos y actividades del calendario académico (campo nombre en la tabla calendario_evento y posible campo dependencia_id para especificación de fechas), la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe analizar el modelo actual de base de datos de eventos [Versión 2,](https://drive.google.com/drive/u/0/folders/1Qtk-kH8iGt-jTpuSo8-lGw05SRiFEhZt), teniendo en cuentas los [mockups](https://docs.google.com/document/d/1wBdNMvz1v1ETFzHFIf3b1Ou-RK79AuXTCEYeonpr_H0/edit) desarrollados por la analista.

- [x] Proponer un modelo de datos que cumpla con los nuevos requerimientos del sistema

- [x] Realizar presentación y autorización del modelo de datos propuestos con DBAS y Arquitectos, junto a líder técnico.

- [x] Realizar su respectiva documentación.

**Comment by ricardoavendano** [comment]
Inicio tareas

**Comment by ricardoavendano** [comment]
Las tareas se encuentran en la siguiente ruta de drive, donde esta el modelo realizado para la tabla nueva calendario, ajuste de campos de las tablas tipo_evento y calendario_evento. En esta carpeta se encuentran los siguientes archivos:
**evento_V_9.png** Imagen del modelo relacional
**evento_V_9.sql** Script para creación del esquema evento con sus tablas y relaciones, realizado para postgresql 9.5
**eventoV9.dbm** Archivo de pgmodel para ver/editar el modelo

Ruta Drive:
https://drive.google.com/drive/u/0/folders/1ETClzuZeP90YIYOWEfTAx8p_voPLi1WI

**Comment by fabianbarreto02** [comment]
Siendo el 27 de octubre del 2020, en una reunión donde asistió: @corio27, @danzola , @fnrojash , @blacburn, @mafeave, @ricardoavendano  y @jupmorenor, se realizo la presentación del ajuste del modelo y se obtuvo aprobación por parte de los arquitectos y los DBAS, donde se sugirió  agregar la relación en la tabla calendario para el manejo de versiones en los calendarios académicos, la cual se realizo y se socializa por este medio.

Se revisa los ajustes realizados al modelo, se da por terminado la issue
