### ISSUE TITLE
Ajustar Api eventos con los cambios del modelo de datos realizados 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/eventos_crud#21]
Se debe realizar los ajustes correspondientes al modelo desarrollado en la issue #20, la issue debe cumplir con lo siguientes requerimientos.

- [x] Ajustar el API de eventos_crud con los ajustes realizados.

- [x] Ajustar los archivos sql para el proceso de migración.

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Ajustar el API de eventos_crud con los ajustes realizados.
commit: dae468770c59b6db630becca9d23bc13054a3914

**Comment by ricardoavendano** [comment]
Ajustar los archivos sql para el proceso de migración.
commit: dae4687
https://drive.google.com/drive/u/0/folders/1ETClzuZeP90YIYOWEfTAx8p_voPLi1WI

**Comment by fabianbarreto02** [comment]
Se realiza ajustes al error
