### ISSUE TITLE
Ajustes de fechas en api de eventos, con la libreria de time bogota 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/eventos_crud#24]
Se debe realizar los ajustes a a lo modelos y controladores para el manejo de la hora de Bogotá, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar modelos del api para manejo de la librería time Bogotá  
 [ ] Ajustar controladores del api para manejo de la librería time Bogotá

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Ajustar modelos del api para manejo de la librería time Bogotá
Se usa udistrital/refactor_controller
commit: dae4687

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de los ajustes solicitados
