### ISSUE TITLE
Crear tabla de rompimiento para los tipos de publico y actividades 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/eventos_crud#31]
Se debe ajusta el modelo de datos, con una tabla de rompimiento entre calendario_evento y tipo publico para relacionar varios publicos a una actividad, la issue debe cumplir con los siguiente requerimientos:

- [x] Ajustas el modelo de datos, con su respectiva documentación,

- [x] Ajustar el api crud con el modemo y controlador nuevo creado y actulizar las rutas

- [x] Crear los respectivos archivos migrations con los ajustes realizados.

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se ajustan issues
Ajustas el modelo de datos, con su respectiva documentación
https://drive.google.com/drive/u/0/folders/13LT-frANXRN6VscPavXCv2CsMtjiNgE3

Ajustar el api crud con el modemo y controlador nuevo creado y actulizar las rutas
Crear los respectivos archivos migrations con los ajustes realizados.
Commit: 8909b5fb435028cbef7ce2a0faadff2b460744f5

**Comment by ricardoavendano** [comment]
Ajuste FechaCreacion y FechaModificacion
commit: 8c01bf6f8bc72e8a6344d806a9f4a36e6d52db61

**Comment by fabianbarreto02** [comment]
Se revisa la creación, migrate y ajustes solicitados, se realiza despliegue en ambiente de pruebas
